### ISSUE TITLE
Add edit password option

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#61]
Third of many issues for #40 project.

Add a new page to edit password, give an option for each password to go to this page. 

1. Move the Rotate AES Key + IV button to this page.
2. Move the Rotate Charset button to this page.
3. Move delete password button to this page.
4. Provide a select box (that loads all existing policies, with current policy selected as default), and an option to choose other policies.

On clicking edit, after selecting a policy in number 4, stay in the same page.

**Comment by 0hmX** [comment]
hey, would love if you could assign me this issue! @frankhart2018

**Comment by frankhart2018** [comment]
Assigning :)

**Comment by frankhart2018** [comment]
Any updates on this @cu8code? I am looking to cut a 0.5 build by mid next week, and this is one of the features that will go into 0.5.

**Comment by navneetthakor** [comment]
Hello @frankhart2018,

I am interested in working on this issue. I had previously implemented password related functionality in 3 projects that you can see on my github page, that's why I am confident in my ability to provide a valuable contribution. Can you please assign this issue to me under Gssoc'24

**Comment by 0hmX** [comment]
@navneetthakor :+1:

**Comment by navneetthakor** [comment]
Sure, I will be happy to contribute in this project

**Comment by frankhart2018** [comment]
Assigned
